#ifndef PANEL_RAMLOG_PROJECT_CONF_H_
#define PANEL_RAMLOG_PROJECT_CONF_H_

/* Match the existing examples/4eMac/rpl-udp project settings. */
#define UIP_CONF_DS6_DEFAULT_PREFIX 0xfd00
#define IEEE802154_CONF_PANID 0xbaba
#define FOURE802154_CONF_PANID IEEE802154_CONF_PANID
/* Keep bootstrap EBs frequent enough for all simulated motes to join quickly. */
#define MIN_CONF_EB_INTERVAL_MUL_START_VAL 1
#define MAX_CONF_EB_INTERVAL_MUL_START_VAL 2
#define FOURE_CONF_NUM_EB_TO_WAIT 2
#define FOURE_CONF_MAX_JOIN_TIME 20
#define SLOT_CONF_FRAME_SIZE 21
#define FOURE_CONF_HARD_SLOTS \
  { {0, 0, SLOT_TYPE_TIMEKEEP}, {8, 0, SLOT_TYPE_SHARED}, \
    {16, 0, SLOT_TYPE_SHARED} }
#define FOURE_CONF_DEFAULT_TIMESLOT_LENGTH 15000
#define UIP_CONF_MAX_ROUTES 20
#define NBR_TABLE_CONF_MAX_NEIGHBORS 8
#define FOURE_CONF_MAX_CONTENT 10
#define FOURE_CONF_MAX_SLOTS_PER_DESTINATION 10

#define SICSLOWPAN_CONF_FRAG 0
#define UIP_CONF_BUFFER_SIZE 160

#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_ERR
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_ERR
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_ERR
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_ERR
#define LOG_CONF_LEVEL_FRAMER LOG_LEVEL_ERR
#define LOG_CONF_LEVEL_4EMAC LOG_LEVEL_INFO

#endif /* PANEL_RAMLOG_PROJECT_CONF_H_ */
